# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

environment:
  matrix:
    - nodejs_version: "6"
      platform: x64
    - nodejs_version: "8"
      platform: x64
    - nodejs_version: "10"
      platform: x64
    - nodejs_version: "12"
      platform: x64
    - nodejs_version: "6"
      platform: x86
    - nodejs_version: "8"
      platform: x86
    - nodejs_version: "10"
      platform: x86
    - nodejs_version: "12"

matrix:
  fast_finish: true

install:
  # Build
  - npm install

cache:
  # local npm modules
  - 'node_modules -> package.json'
  # npm cache
  - '%APPDATA%\npm-cache'

build: off

test: off

deploy: off
